/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vuelouy.interfaz.common;

import java.util.Locale;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author alumnoFI
 */
public class MenuConfiguracionPasajero extends javax.swing.JPanel implements Observer{

    private boolean volumen;
    private ComunicacionPaneles comunicacion;

    /**
     *
     */
    public MenuConfiguracionPasajero() {
        initComponents();
        volumen = true;
    }
    
    /**
     *
     * @param cp
     */
    public MenuConfiguracionPasajero(ComunicacionPaneles cp) {
        comunicacion = cp;
        comunicacion.addObserver(this);
        initComponents();
        volumen = true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEspaniol = new javax.swing.JButton();
        btnIng = new javax.swing.JButton();
        lblConfig = new javax.swing.JLabel();
        lblIdioma = new javax.swing.JLabel();

        btnEspaniol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/IdiomaEsp.png"))); // NOI18N
        btnEspaniol.setBorder(null);
        btnEspaniol.setBorderPainted(false);
        btnEspaniol.setContentAreaFilled(false);
        btnEspaniol.setPreferredSize(new java.awt.Dimension(96, 96));
        btnEspaniol.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/IdiomaEspP.png"))); // NOI18N
        btnEspaniol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspaniolActionPerformed(evt);
            }
        });

        btnIng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/IdiomaIng.png"))); // NOI18N
        btnIng.setBorder(null);
        btnIng.setBorderPainted(false);
        btnIng.setContentAreaFilled(false);
        btnIng.setPreferredSize(new java.awt.Dimension(96, 96));
        btnIng.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/IdiomaEngP.png"))); // NOI18N
        btnIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngActionPerformed(evt);
            }
        });

        lblConfig.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vuelouy/interfaz/common/Bundle"); // NOI18N
        lblConfig.setText(bundle.getString("MenuConfiguracionPasajero.lblConfig.text")); // NOI18N

        lblIdioma.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblIdioma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdioma.setText(bundle.getString("MenuConfiguracionPasajero.lblIdioma.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblConfig))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(btnEspaniol, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179)
                        .addComponent(btnIng, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblIdioma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfig)
                .addGap(54, 54, 54)
                .addComponent(lblIdioma)
                .addGap(197, 197, 197)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIng, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEspaniol, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEspaniolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspaniolActionPerformed
        comunicacion.setIdioma(Locale.getDefault());
        comunicacion.cambio();
    }//GEN-LAST:event_btnEspaniolActionPerformed

    
    private void btnIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngActionPerformed
        Locale locale = new Locale("en","Us");
        comunicacion.setIdioma(locale);
        comunicacion.cambio();
    }//GEN-LAST:event_btnIngActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEspaniol;
    private javax.swing.JButton btnIng;
    private javax.swing.JLabel lblConfig;
    private javax.swing.JLabel lblIdioma;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        lblIdioma.setText(comunicacion.obtenerValorTraducido("MenuConfiguracionPasajero.lblIdioma.text"));
        lblConfig.setText(comunicacion.obtenerValorTraducido("MenuConfiguracionPasajero.lblConfig.text"));
    }
}
