/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vuelouy.interfaz.common;

import java.util.Locale;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author alumnoFI
 */
public class MenuConfiguracionPasajero extends javax.swing.JPanel implements Observer{

    private boolean volumen;
    private ComunicacionPaneles comunicacion;

    /**
     *
     */
    public MenuConfiguracionPasajero() {
        initComponents();
        volumen = true;
    }
    
    /**
     *
     * @param cp
     */
    public MenuConfiguracionPasajero(ComunicacionPaneles cp) {
        comunicacion = cp;
        comunicacion.addObserver(this);
        initComponents();
        volumen = true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEspaniol = new javax.swing.JButton();
        btnIng = new javax.swing.JButton();
        lblConfig = new javax.swing.JLabel();
        lblIdioma = new javax.swing.JLabel();
        btnFrances = new javax.swing.JButton();
        btnAleman = new javax.swing.JButton();
        btnItaliano = new javax.swing.JButton();

        btnEspaniol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/IdiomaEsp.png"))); // NOI18N
        btnEspaniol.setBorder(null);
        btnEspaniol.setBorderPainted(false);
        btnEspaniol.setContentAreaFilled(false);
        btnEspaniol.setPreferredSize(new java.awt.Dimension(96, 96));
        btnEspaniol.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/IdiomaEspP.png"))); // NOI18N
        btnEspaniol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspaniolActionPerformed(evt);
            }
        });

        btnIng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/IdiomaIng.png"))); // NOI18N
        btnIng.setBorder(null);
        btnIng.setBorderPainted(false);
        btnIng.setContentAreaFilled(false);
        btnIng.setPreferredSize(new java.awt.Dimension(96, 96));
        btnIng.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/IdiomaEngP.png"))); // NOI18N
        btnIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngActionPerformed(evt);
            }
        });

        lblConfig.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vuelouy/interfaz/common/Bundle"); // NOI18N
        lblConfig.setText(bundle.getString("MenuConfiguracionPasajero.lblConfig.text")); // NOI18N

        lblIdioma.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblIdioma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdioma.setText(bundle.getString("MenuConfiguracionPasajero.lblIdioma.text")); // NOI18N

        btnFrances.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/IdiomaFra.png"))); // NOI18N
        btnFrances.setBorder(null);
        btnFrances.setBorderPainted(false);
        btnFrances.setContentAreaFilled(false);
        btnFrances.setPreferredSize(new java.awt.Dimension(96, 96));
        btnFrances.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/IdiomaFraP.png"))); // NOI18N
        btnFrances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrancesActionPerformed(evt);
            }
        });

        btnAleman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/IdiomaAleman.png"))); // NOI18N
        btnAleman.setBorder(null);
        btnAleman.setBorderPainted(false);
        btnAleman.setContentAreaFilled(false);
        btnAleman.setPreferredSize(new java.awt.Dimension(96, 96));
        btnAleman.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/IdiomaAlemanP.png"))); // NOI18N
        btnAleman.setRequestFocusEnabled(false);
        btnAleman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlemanActionPerformed(evt);
            }
        });

        btnItaliano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/IdiomaItaliano.png"))); // NOI18N
        btnItaliano.setBorder(null);
        btnItaliano.setBorderPainted(false);
        btnItaliano.setContentAreaFilled(false);
        btnItaliano.setPreferredSize(new java.awt.Dimension(96, 96));
        btnItaliano.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/IdiomaItalianoP.png"))); // NOI18N
        btnItaliano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItalianoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblIdioma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfig)
                .addGap(411, 411, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFrances, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAleman, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEspaniol, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIng, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnItaliano, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfig)
                .addGap(54, 54, 54)
                .addComponent(lblIdioma)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEspaniol, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIng, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnItaliano, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFrances, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAleman, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEspaniolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspaniolActionPerformed
        comunicacion.setIdioma(Locale.getDefault());
        comunicacion.cambio();
    }//GEN-LAST:event_btnEspaniolActionPerformed

    
    private void btnIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngActionPerformed
        comunicacion.setIdioma(Locale.US);
        comunicacion.cambio();
    }//GEN-LAST:event_btnIngActionPerformed

    private void btnFrancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrancesActionPerformed
        comunicacion.setIdioma(Locale.FRANCE);
        comunicacion.cambio();
    }//GEN-LAST:event_btnFrancesActionPerformed

    private void btnAlemanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlemanActionPerformed
        comunicacion.setIdioma(Locale.GERMANY);
        comunicacion.cambio();
    }//GEN-LAST:event_btnAlemanActionPerformed

    private void btnItalianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItalianoActionPerformed
        comunicacion.setIdioma(Locale.ITALY);
        comunicacion.cambio();
    }//GEN-LAST:event_btnItalianoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAleman;
    private javax.swing.JButton btnEspaniol;
    private javax.swing.JButton btnFrances;
    private javax.swing.JButton btnIng;
    private javax.swing.JButton btnItaliano;
    private javax.swing.JLabel lblConfig;
    private javax.swing.JLabel lblIdioma;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        lblIdioma.setText(comunicacion.obtenerValorTraducido("MenuConfiguracionPasajero.lblIdioma.text"));
        lblConfig.setText(comunicacion.obtenerValorTraducido("MenuConfiguracionPasajero.lblConfig.text"));
    }
}
