/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vuelouy.interfaz.common;

import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import vuelouy.archivos.ManejadorArchivos;
import vuelouy.dominio.Libro;

/**
 *
 * @author alumnoFI
 */
public class MenuRevistas extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form MenuRevistas
     *
     */
    private ComunicacionPaneles comunicacion;
    private List<Libro> libros;

    /**
     *
     */
    public MenuRevistas() {
        initComponents();
    }

    /**
     *
     * @param p
     */
    public MenuRevistas(ComunicacionPaneles p) {
        comunicacion = p;
        comunicacion.addObserver(this);
        initComponents();
        cargarLibros();
    }
    
    private void cargarLibros(){
        ManejadorArchivos m = new ManejadorArchivos();
        libros = m.obetenerLibros(comunicacion.getIdioma().getLanguage());
        DefaultListModel listModel = new DefaultListModel();
        for (Libro libro : libros) {
            listModel.addElement(libro.getTitulo());
        }
        jListLibros.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVolver = new javax.swing.JButton();
        lblLectura = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jepLectura = new javax.swing.JEditorPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListLibros = new javax.swing.JList<>();
        jButtonLeer = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(664, 548));

        jButtonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Volver.png"))); // NOI18N
        jButtonVolver.setBorder(null);
        jButtonVolver.setBorderPainted(false);
        jButtonVolver.setContentAreaFilled(false);
        jButtonVolver.setPreferredSize(new java.awt.Dimension(96, 96));
        jButtonVolver.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/VolverP.png"))); // NOI18N
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        lblLectura.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vuelouy/interfaz/common/Bundle"); // NOI18N
        lblLectura.setText(bundle.getString("MenuRevistas.lblLectura.text")); // NOI18N

        jepLectura.setEditable(false);
        jepLectura.setContentType("text/html"); // NOI18N
        jScrollPane2.setViewportView(jepLectura);

        jListLibros.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListLibros);

        jButtonLeer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Leer.png"))); // NOI18N
        jButtonLeer.setBorder(null);
        jButtonLeer.setBorderPainted(false);
        jButtonLeer.setContentAreaFilled(false);
        jButtonLeer.setPreferredSize(new java.awt.Dimension(96, 96));
        jButtonLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLectura)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonLeer, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLectura)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        comunicacion.setPanel("Entretenimiento");
        comunicacion.setBPanel(true);
        comunicacion.cambio();
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeerActionPerformed
        String tituloSeleccionado = jListLibros.getSelectedValue();
        for (Libro libro : libros) {
            if(libro.getTitulo().equals(tituloSeleccionado)){
                jepLectura.setText(libro.getContenido());
                break;
            }
        }
    }//GEN-LAST:event_jButtonLeerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLeer;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JList<String> jListLibros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JEditorPane jepLectura;
    private javax.swing.JLabel lblLectura;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (comunicacion.getBPanel()) {
            this.setVisible(false);
            comunicacion.getVentanaInicioP().mostrarSubMenu(comunicacion.getPanel());
        }
        lblLectura.setText(comunicacion.obtenerValorTraducido("MenuRevistas.lblLectura.text"));
        cargarLibros();
        jepLectura.setText("");
    }
}
