/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vuelouy.interfaz.common;

import vuelouy.dominio.Viaje;
import java.util.Calendar;
import static java.util.Calendar.getInstance;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author alumnoFI
 */
public class MenuConfiguracionTripulante extends javax.swing.JPanel {

    /**
     * Creates new form MenuConfiguracionPiloto
     */
    private Viaje viaje;
    private final ComunicacionPaneles comunicacion = ComunicacionPaneles.getInstance();
    
    /**
     *
     */
    public MenuConfiguracionTripulante() {
        initComponents();
    }
    
    /**
     *
     * @param unViaje
     */
    public MenuConfiguracionTripulante(Viaje unViaje) {
        viaje = unViaje;
        initComponents();
        lblDestinoError.setText("");
        lblOrigenError.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbOrigen = new javax.swing.JComboBox();
        cbHoraDuracion = new javax.swing.JComboBox();
        cbDestino = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cbMinutoDuracion = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cbNroAsiento = new javax.swing.JComboBox();
        cbNombrePasajero = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDestinoError = new javax.swing.JLabel();
        btnConfirmacion = new javax.swing.JButton();
        lblOrigenError = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);

        jLabel7.setText("Número de Asiento: ");

        cbOrigen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Montevideo", "Buenos Aires", "Madrid", "Paris" }));
        cbOrigen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbOrigenItemStateChanged(evt);
            }
        });

        cbHoraDuracion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbHoraDuracion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbHoraDuracionItemStateChanged(evt);
            }
        });

        cbDestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buenos Aires", "Madrid", "Paris", "Montevideo" }));
        cbDestino.setToolTipText("");
        cbDestino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDestinoItemStateChanged(evt);
            }
        });

        jLabel1.setText("Origen:");

        cbMinutoDuracion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "15", "30", "45" }));
        cbMinutoDuracion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMinutoDuracionItemStateChanged(evt);
            }
        });

        jLabel4.setText("Duración Viaje: ");

        cbNroAsiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "15", "33", "45", "68", "72" }));
        cbNroAsiento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNroAsientoItemStateChanged(evt);
            }
        });

        cbNombrePasajero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ramon", "Juan", "Pedro", "María", "Andrea", "Ana" }));
        cbNombrePasajero.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNombrePasajeroItemStateChanged(evt);
            }
        });

        jLabel6.setText("Nombre de Pasajero: ");

        jLabel3.setText("Destino:");

        lblDestinoError.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblDestinoError.setForeground(new java.awt.Color(102, 102, 102));
        lblDestinoError.setText("error destino");

        btnConfirmacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnConfirmacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/Btn.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("vuelouy/interfaz/common/Bundle"); // NOI18N
        btnConfirmacion.setText(bundle.getString("MenuPedidos.btnMerienda.text")); // NOI18N
        btnConfirmacion.setBorder(null);
        btnConfirmacion.setBorderPainted(false);
        btnConfirmacion.setContentAreaFilled(false);
        btnConfirmacion.setFocusable(false);
        btnConfirmacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConfirmacion.setPreferredSize(new java.awt.Dimension(125, 96));
        btnConfirmacion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/vuelouy/image/BtnP.png"))); // NOI18N
        btnConfirmacion.setRolloverEnabled(false);
        btnConfirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmacionActionPerformed(evt);
            }
        });

        lblOrigenError.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lblOrigenError.setForeground(new java.awt.Color(102, 102, 102));
        lblOrigenError.setText("error destino");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(6, 6, 6))
                                .addComponent(jLabel6))
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbNroAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbHoraDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbMinutoDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbNombrePasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOrigenError)
                                    .addComponent(lblDestinoError))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrigenError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDestinoError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbHoraDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMinutoDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbNombrePasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbNroAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addComponent(btnConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Panel de configuración del Sistema de Entretenimiento");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmacionActionPerformed
        if (cbOrigen.getSelectedItem().toString().equals(cbDestino.getSelectedItem().toString())) {
            lblDestinoError.setText("Origen y Destino deben ser diferentes");
            lblOrigenError.setText("Origen y Destino deben ser diferentes");
            showMessageDialog(this, "Existen errores en origen y destino", "Error", JOptionPane.ERROR_MESSAGE);
        }else {
            lblDestinoError.setText("");
            lblOrigenError.setText("");
            viaje.setOrigen(cbOrigen.getSelectedItem().toString());
            viaje.setDestino(cbDestino.getSelectedItem().toString());
            viaje.setNombrePasajero(cbNombrePasajero.getSelectedItem().toString());
            viaje.setAsiento(cbNroAsiento.getSelectedItem().toString());
            actualizarFecha();
            comunicacion.cambio();
        }
    }//GEN-LAST:event_btnConfirmacionActionPerformed

    private void cbNombrePasajeroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNombrePasajeroItemStateChanged

    }//GEN-LAST:event_cbNombrePasajeroItemStateChanged

    private void cbNroAsientoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNroAsientoItemStateChanged

    }//GEN-LAST:event_cbNroAsientoItemStateChanged

    private void cbMinutoDuracionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMinutoDuracionItemStateChanged

    }//GEN-LAST:event_cbMinutoDuracionItemStateChanged

    private void cbDestinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDestinoItemStateChanged
        if (cbOrigen.getSelectedItem().toString().equals(cbDestino.getSelectedItem().toString())) {
            lblDestinoError.setText("Origen y Destino deben ser diferentes");
            lblOrigenError.setText("Origen y Destino deben ser diferentes");
        } else {
            lblDestinoError.setText("");
            lblOrigenError.setText("");
        }
    }//GEN-LAST:event_cbDestinoItemStateChanged

    private void cbHoraDuracionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbHoraDuracionItemStateChanged

    }//GEN-LAST:event_cbHoraDuracionItemStateChanged

    private void cbOrigenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbOrigenItemStateChanged
        if (cbOrigen.getSelectedItem().toString().equals(cbDestino.getSelectedItem().toString())) {
            lblDestinoError.setText("Origen y Destino deben ser diferentes");
            lblOrigenError.setText("Origen y Destino deben ser diferentes");
        } else {
            lblDestinoError.setText("");
            lblOrigenError.setText("");
        }
    }//GEN-LAST:event_cbOrigenItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmacion;
    private javax.swing.JComboBox cbDestino;
    private javax.swing.JComboBox cbHoraDuracion;
    private javax.swing.JComboBox cbMinutoDuracion;
    private javax.swing.JComboBox cbNombrePasajero;
    private javax.swing.JComboBox cbNroAsiento;
    private javax.swing.JComboBox cbOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDestinoError;
    private javax.swing.JLabel lblOrigenError;
    // End of variables declaration//GEN-END:variables

    public void actualizarFecha(){
                int horaPartida = viaje.getFechaPartida()
                        .get(Calendar.HOUR_OF_DAY);
                int minPartida = viaje.getFechaPartida()
                        .get(Calendar.MINUTE);
                int minDuracion = Integer.parseInt
                (cbMinutoDuracion.getSelectedItem().toString());
                int horaDuracion = Integer.parseInt
                (cbHoraDuracion.getSelectedItem().toString());
                
                int diaArribo;
                int horaArribo;
                int minArribo;
                
                if (minPartida + minDuracion >= 60) {
                    minArribo = minPartida + minDuracion - 60;
                    if (horaPartida + horaDuracion >= 23) {
                        diaArribo = viaje.getFechaPartida()
                                .get(Calendar.DAY_OF_MONTH) + 1;
                        horaArribo = horaPartida + horaDuracion - 23;
                    }else{
                        horaArribo = horaPartida + horaDuracion + 1;
                        diaArribo = viaje.getFechaPartida()
                                .get(Calendar.DAY_OF_MONTH);
                    }
                }else{
                    minArribo = minPartida + minDuracion;
                    if (horaPartida + horaDuracion >= 24) {
                        diaArribo = viaje.getFechaPartida()
                                .get(Calendar.DAY_OF_MONTH) + 1;
                        horaArribo = horaPartida + horaDuracion - 24;
                    }else{
                        diaArribo = viaje.getFechaPartida()
                                .get(Calendar.DAY_OF_MONTH);
                        horaArribo = horaPartida + horaDuracion;
                    }
                }
                Calendar fechaArriboNueva = getInstance();
                fechaArriboNueva.set(viaje.getFechaPartida().get(Calendar.YEAR),
                        viaje.getFechaPartida().get(Calendar.MONTH), 
                        diaArribo, horaArribo, minArribo, 0);
                viaje.setFechaArribo(fechaArriboNueva); 
    }
}
